---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: number
  name: order
  label: Order
  description: numerical order of sorting products
- type: file
  name: default_thumbnail_image
  label: Default Thumbnail Image
- type: file
  name: default_original_image
  label: Default Original Image
- type: select
  name: category
  label: Category
  config:
    source:
      type: pages
      section: pages
- type: boolean
  name: featured
  label: Featured
  default: false
- type: field_group
  name: seo
  label: Seo
  fields:
  - type: include
    name: include_stackbit_page_meta
    label: Page meta data
    template: stackbit_page_meta
- type: text
  name: template
  label: Template
  hidden: true
  default: product
  config:
    required: true
pages:
- src/pages/hills-perro-puppy-small-bites-4.5-lb-2-kg.md
- src/pages/products/diamond-18-lbs.senior-8-naturals-8.164-kgs.md
- src/pages/products/diamond-20-lbs-adulto-premium-9.72-kgs.md
- src/pages/products/diamond-20-lbs-lamb-meal-rice-adult-9.72-kgs.md
- src/pages/products/diamond-20-lbs-large-breed-puppy-lamb-rice-9.72-kgs.md
- src/pages/products/diamond-20-lbs-puppy-9.72-kgs.md
- src/pages/products/diamond-40-lbs-adulto-maintenance-18.144-kgs.md
- src/pages/products/diamond-40-lbs-adulto-premium-18.144-kgs.md
- src/pages/products/diamond-40-lbs-lamb-meal-rice-adult-18.144-kgs.md
- src/pages/products/diamond-40-lbs-large-breed-puppy-lamb-rice-18.144-kgs.md
- src/pages/products/diamond-6-lbs.lamb-meal-rice-adult-2.722-kgs.md
- src/pages/products/diamond-8-lbs-adulto-premium-3.629-kgs.md
- src/pages/products/diamond-8-lbs-puppy-3.629-kgs.md
- src/pages/products/hills-gato-adult-hairball-control-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-hairball-control-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-adult-hairball-control-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-hairball-control-light-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-indoor-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-indoor-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-adult-indoor-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-multi-benefit-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-multi-benefit-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-original-16-lb-7.3-kg.md
- src/pages/products/hills-gato-adult-original-4-lb-1.8-kg.md
- src/pages/products/hills-gato-adult-original-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-original-light-16-lb-7.3-kg.md
- src/pages/products/hills-gato-adult-original-light-7-lb-3.2-kg.md
- src/pages/products/hills-gato-c-d-multicare-4-lb-1.8-kg.md
- src/pages/products/hills-gato-c-d-multicare-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-c-d-multicare-stress-4-lb-1.8-kg.md
- src/pages/products/hills-gato-gi-biome-4-lb-1.8-kg.md
- src/pages/products/hills-gato-i-d-4-lb-1.8-kg.md
- src/pages/products/hills-gato-k-d-4-lb-1.8-kg.md
- src/pages/products/hills-gato-k-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-kitten-indoor-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-kitten-indoor-7-lb-3.2-kg.md
- src/pages/products/hills-gato-kitten-original-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-kitten-original-7-lb-3.2-kg.md
- src/pages/products/hills-gato-metabolic-17.6-lb-8-kg.md
- src/pages/products/hills-gato-metabolic-4-lb-1.8-kg.md
- src/pages/products/hills-gato-metabolic-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-metabolic-urinary-6.4-lb-2.9-kg.md
- src/pages/products/hills-gato-perro-a-d-lata-0.34-lb-0.15-kg.md
- src/pages/products/hills-gato-r-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-s-d-4-lb-1.8-kg.md
- src/pages/products/hills-gato-w-d-multibenefit-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-z-d-4-lb-1.8-kg.md
- src/pages/products/hills-perro-adult-light-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-light-30-lb-13.6-kg.md
- src/pages/products/hills-perro-adult-original-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-original-35-lb-15.9-kg.md
- src/pages/products/hills-perro-adult-original-5-lb-2.3-kg.md
- src/pages/products/hills-perro-adult-original-lamb-rice-33-lb-15-kg.md
- src/pages/products/hills-perro-adult-small-bites-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-small-bites-5-lb-2.3-kg.md
- src/pages/products/hills-perro-adult-small-paws-15.5-lb-7-kg.md
- src/pages/products/hills-perro-adult-small-paws-4.5-lb-2-kg.md
- src/pages/products/hills-perro-adult-small-paws-light-15.5-lb-7-kg.md
- src/pages/products/hills-perro-adult-small-paws-light-4.5-lb-2-kg.md
- src/pages/products/hills-perro-c-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-c-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-c-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-c-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-d-d-25-lb-11.3-kg.md
- src/pages/products/hills-perro-d-d-8-lb-3.6-kg.md
- src/pages/products/hills-perro-derm-defense-25-lb-11.3-kg.md
- src/pages/products/hills-perro-derm-defense-6-lb-2.7-kg.md
- src/pages/products/hills-perro-gi-biome-16-lb-7.2-kg.md
- src/pages/products/hills-perro-gi-biome-8-lb-3.6-kg.md
- src/pages/products/hills-perro-h-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-h-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-i-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-i-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-i-d-low-fat-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-i-d-small-bites-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-j-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-k-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-k-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-k-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-k-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-l-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-metabolic-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-metabolic-7.7-lb-3.5-kg.md
- src/pages/products/hills-perro-metabolic-mobility-24-lb-10.9-kg.md
- src/pages/products/hills-perro-metabolic-mobility-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-puppy-large-breed-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-large-breed-30-lb-13.6-kg.md
- src/pages/products/hills-perro-puppy-original-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-original-30-lb-13.6-kg.md
- src/pages/products/hills-perro-puppy-original-4.5-lb-2-kg.md
- src/pages/products/hills-perro-puppy-original-lata-0.82-lb-0.37-kg.md
- src/pages/products/hills-perro-puppy-small-bites-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-small-paws-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-small-paws-4.5-lb-2-kg.md
- src/pages/products/hills-perro-r-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-r-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-r-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-r-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-senior-vitality-7-12.5-lb-5.7-kg.md
- src/pages/products/hills-perro-senior-vitality-7-3.5-lb-1.6-kg.md
- src/pages/products/hills-perro-senior-vitality-7-5.95-lb-2.7-kg.md
- src/pages/products/hills-perro-u-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-u-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-w-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-w-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-w-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-w-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-z-d-ultra-17.6-lb-8-kg.md
- src/pages/products/hills-perro-z-d-ultra-8-lb-3.6-kg.md
- src/pages/products/plant1.md
- src/pages/products/plant2.md
- src/pages/products/plant3.md
- src/pages/products/plant4.md
- src/pages/products/plant5.md
- src/pages/products/plant6.md
- src/pages/products/plant7.md
- src/pages/products/plant8.md
- src/pages/products/plant9.md
- src/pages/products/pro-plan-adulto-performance-todas-las-razas-13-kg.md
- src/pages/products/pro-plan-adulto-raza-grande-13-kg.md
- src/pages/products/pro-plan-adulto-raza-grande-3-kg.md
- src/pages/products/pro-plan-adulto-raza-mediana-13-kg.md
- src/pages/products/pro-plan-adulto-raza-mediana-3-kg.md
- src/pages/products/pro-plan-adulto-raza-mediana-7.5-kg.md
- src/pages/products/pro-plan-adulto-raza-pequena-3.5-kg.md
- src/pages/products/pro-plan-adulto-raza-pequena-7.5-kg.md
- src/pages/products/pro-plan-adulto-raza-pequena-delicate-structure-3-kg.md
- src/pages/products/pro-plan-adulto-raza-pequena-exigent-3-kg.md
- src/pages/products/pro-plan-adulto-sensitive-digestion-todas-las-razas-10-kg.md
- src/pages/products/pro-plan-adulto-sensitive-digestion-todas-las-razas-3.5-kg.md
- src/pages/products/pro-plan-cachorro-raza-grande-13-kg.md
- src/pages/products/pro-plan-cachorro-raza-grande-3.5-kg.md
- src/pages/products/pro-plan-cachorro-raza-mediana-13-kg.md
- src/pages/products/pro-plan-cachorro-raza-mediana-3-kg.md
- src/pages/products/pro-plan-cachorro-raza-mediana-7.5-kg.md
- src/pages/products/pro-plan-cachorro-raza-pequena-3.5-kg.md
- src/pages/products/pro-plan-cachorro-raza-pequena-7.5-kg.md
- src/pages/products/pro-plan-fortiflora-canine-1.06-oz-us-30-sobres-1-gr.md
- src/pages/products/pro-plan-gatito-1.5-kg.md
- src/pages/products/pro-plan-gatito-3.0-kg.md
- src/pages/products/pro-plan-gato-adulto-3-kg.md
- src/pages/products/pro-plan-gato-adulto-7.5-kg.md
- src/pages/products/pro-plan-gato-adulto-reduced-calorie-3-kg.md
- src/pages/products/pro-plan-gato-adulto-senior-7-3-kg.md
- src/pages/products/pro-plan-gato-adulto-sensitive-3-kg.md
- src/pages/products/pro-plan-gato-adulto-sterilized-3-kg.md
- src/pages/products/pro-plan-gato-adulto-urinary-3-kg.md
- src/pages/products/pro-plan-gato-dh-feline-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-gato-dm-feline-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-gato-feline-en-6-lb-2.72-kg.md
- src/pages/products/pro-plan-gato-feline-ha-4-lb-us-1.81-kg.md
- src/pages/products/pro-plan-gato-feline-om-6-lb-us-2.72-kg.md
- src/pages/products/pro-plan-gato-fortiflora-feline-1.06-oz-us-30-sobres-1-gr.md
- src/pages/products/pro-plan-gato-nf-advance-care-feline-3.62kg.md
- src/pages/products/pro-plan-gato-nf-early-care-feline-3.62-kg.md
- src/pages/products/pro-plan-gato-ur-feline-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-light-adulto-reduced-calorie-todas-las-razas-13-kg.md
- src/pages/products/pro-plan-light-adulto-reduced-calorie-todas-las-razas-3-kg.md
- src/pages/products/pro-plan-perro-canine-en-18-lb-us-8.16-kg.md
- src/pages/products/pro-plan-perro-canine-en-6-lb-us-2.72-kg.md
- src/pages/products/pro-plan-perro-canine-ha-16.5-lb-us-7.48-kg.md
- src/pages/products/pro-plan-perro-canine-ha-6-lb-us-2.72-kg.md
- src/pages/products/pro-plan-perro-canine-nf-18-lb-us-8.16-kg.md
- src/pages/products/pro-plan-perro-canine-nf-6-lb-us-2.72-kg.md
- src/pages/products/pro-plan-perro-canine-om-18-lb-us-8.16-kg.md
- src/pages/products/pro-plan-perro-canine-om-6-lb-us-2.72-kg.md
- src/pages/products/pro-plan-perro-dh-canine-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-perro-drm-naturals-canine-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-perro-en-fiber-balance-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-perro-en-low-fat-canine-6-lb-2.72-kg.md
- src/pages/products/pro-plan-perro-jm-canine-dry-18-lb-8.16-kg.md
- src/pages/products/pro-plan-perro-jm-canine-dry-6-lb-2.72-kg.md
- src/pages/products/pro-plan-perro-nc-canine-11.3-kg.md
- src/pages/products/pro-plan-perro-nc-canine-2.72-kg.md
- src/pages/products/pro-plan-perro-nc-canine-4.9-kg.md
- src/pages/products/pro-plan-perro-ur-canine-16.5-lb-7.48-kg.md
- src/pages/products/pro-plan-perro-ur-canine-2.72-kg.md
- src/pages/products/pro-plan-salmon-adulto-raza-mediana-grande-sensitive-skin-13-kg.md
- src/pages/products/pro-plan-salmon-adulto-raza-mediana-grande-sensitive-skin-3-kg.md
- src/pages/products/pro-plan-salmon-adulto-raza-pequena-sensitive-skin-3-kg.md
- src/pages/products/pro-plan-salmon-adulto-raza-pequena-sensitive-skin-7.5-kg.md
- src/pages/products/pro-plan-salmon-cachorro-sensitive-skin-todas-las-razas-13-kg.md
- src/pages/products/pro-plan-salmon-cachorro-sensitive-skin-todas-las-razas-3-kg.md
- src/pages/products/pro-plan-senior-raza-pequena-active-mind-3-kg.md
- src/pages/products/pro-plan-senior-raza-pequena-active-mind-7.5-kg.md
- src/pages/products/pro-plan-senior-razas-medianas-y-grandes-active-mind-13-kg.md
- src/pages/products/pro-plan-senior-razas-medianas-y-grandes-active-mind-3-kg.md
- src/pages/products/pro-plan-senior-razas-medianas-y-grandes-active-mind-7.5-kg.md
- src/pages/products/purina-excellent-adulto-cachorro-complete-15-kg.md
- src/pages/products/purina-excellent-adulto-cachorro-complete-20-kg.md
- src/pages/products/purina-excellent-adulto-complete-15-kg.md
- src/pages/products/purina-excellent-adulto-complete-20-kg.md
- src/pages/products/purina-excellent-adulto-complete-4-kg.md
- src/pages/products/purina-excellent-adulto-cordero-20.4-kg.md
- src/pages/products/purina-excellent-adulto-raza-pequena-3.5-kg.md
- src/pages/products/purina-excellent-adulto-raza-pequena-7.5-kg.md
- src/pages/products/purina-excellent-cachorro-excellent-raza-pequena-4-kg.md
- src/pages/products/purina-excellent-cachorro-excellent-raza-pequena-7.5-kg.md
