---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: number
  name: order
  label: Order
  description: numerical order of sorting products
- type: file
  name: default_thumbnail_image
  label: Default Thumbnail Image
- type: file
  name: default_original_image
  label: Default Original Image
- type: select
  name: category
  label: Category
  config:
    source:
      type: pages
      section: pages
- type: boolean
  name: featured
  label: Featured
  default: false
- type: field_group
  name: seo
  label: Seo
  fields:
  - type: include
    name: include_stackbit_page_meta
    label: Page meta data
    template: stackbit_page_meta
- type: text
  name: template
  label: Template
  hidden: true
  default: product
  config:
    required: true
pages:
- src/pages/hills-perro-puppy-small-bites-4.5-lb-2-kg.md
- src/pages/products/adulto-excellent-raza-pequena-3.5kg.md
- src/pages/products/diamond-18-lbs.senior-8-naturals-8.164-kgs.md
- src/pages/products/diamond-20-lbs-adulto-premium-9.72-kgs.md
- src/pages/products/diamond-20-lbs-lamb-meal-rice-adult-9.72-kgs.md
- src/pages/products/diamond-20-lbs-large-breed-puppy-lamb-rice-9.72-kgs.md
- src/pages/products/diamond-20-lbs-puppy-9.72-kgs.md
- src/pages/products/diamond-40-lbs-adulto-maintenance-18.144-kgs.md
- src/pages/products/diamond-40-lbs-adulto-premium-18.144-kgs.md
- src/pages/products/diamond-40-lbs-lamb-meal-rice-adult-18.144-kgs.md
- src/pages/products/diamond-40-lbs-large-breed-puppy-lamb-rice-18.144-kgs.md
- src/pages/products/diamond-6-lbs.lamb-meal-rice-adult-2.722-kgs.md
- src/pages/products/diamond-8-lbs-adulto-premium-3.629-kgs.md
- src/pages/products/diamond-8-lbs-puppy-3.629-kgs.md
- src/pages/products/hills-gato-adult-hairball-control-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-hairball-control-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-adult-hairball-control-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-hairball-control-light-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-indoor-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-indoor-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-adult-indoor-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-multi-benefit-15.5-lb-7-kg.md
- src/pages/products/hills-gato-adult-multi-benefit-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-original-16-lb-7.3-kg.md
- src/pages/products/hills-gato-adult-original-4-lb-1.8-kg.md
- src/pages/products/hills-gato-adult-original-7-lb-3.2-kg.md
- src/pages/products/hills-gato-adult-original-light-16-lb-7.3-kg.md
- src/pages/products/hills-gato-adult-original-light-7-lb-3.2-kg.md
- src/pages/products/hills-gato-c-d-multicare-4-lb-1.8-kg.md
- src/pages/products/hills-gato-c-d-multicare-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-c-d-multicare-stress-4-lb-1.8-kg.md
- src/pages/products/hills-gato-gi-biome-4-lb-1.8-kg.md
- src/pages/products/hills-gato-i-d-4-lb-1.8-kg.md
- src/pages/products/hills-gato-k-d-4-lb-1.8-kg.md
- src/pages/products/hills-gato-k-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-kitten-indoor-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-kitten-indoor-7-lb-3.2-kg.md
- src/pages/products/hills-gato-kitten-original-3.5-lb-1.6-kg.md
- src/pages/products/hills-gato-kitten-original-7-lb-3.2-kg.md
- src/pages/products/hills-gato-metabolic-4-lb-1.8-kg.md
- src/pages/products/hills-gato-metabolic-8.5-lb-3.9-kg.md
- src/pages/products/hills-gato-perro-a-d-lata-0.34-lb-0.15-kg.md
- src/pages/products/hills-perro-adult-light-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-light-30-lb-13.6-kg.md
- src/pages/products/hills-perro-adult-original-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-original-35-lb-15.9-kg.md
- src/pages/products/hills-perro-adult-original-5-lb-2.3-kg.md
- src/pages/products/hills-perro-adult-original-lamb-rice-33-lb-15-kg.md
- src/pages/products/hills-perro-adult-small-bites-15-lb-6.8-kg.md
- src/pages/products/hills-perro-adult-small-bites-5-lb-2.3-kg.md
- src/pages/products/hills-perro-adult-small-paws-15.5-lb-7-kg.md
- src/pages/products/hills-perro-adult-small-paws-4.5-lb-2-kg.md
- src/pages/products/hills-perro-adult-small-paws-light-15.5-lb-7-kg.md
- src/pages/products/hills-perro-adult-small-paws-light-4.5-lb-2-kg.md
- src/pages/products/hills-perro-c-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-c-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-c-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-c-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-d-d-25-lb-11.3-kg.md
- src/pages/products/hills-perro-d-d-8-lb-3.6-kg.md
- src/pages/products/hills-perro-derm-defense-25-lb-11.3-kg.md
- src/pages/products/hills-perro-derm-defense-6-lb-2.7-kg.md
- src/pages/products/hills-perro-gi-biome-16-lb-7.2-kg.md
- src/pages/products/hills-perro-gi-biome-8-lb-3.6-kg.md
- src/pages/products/hills-perro-h-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-h-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-i-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-i-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-i-d-low-fat-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-i-d-small-bites-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-j-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-k-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-k-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-k-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-k-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-l-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-metabolic-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-metabolic-7.7-lb-3.5-kg.md
- src/pages/products/hills-perro-metabolic-mobility-24-lb-10.9-kg.md
- src/pages/products/hills-perro-metabolic-mobility-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-puppy-large-breed-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-large-breed-30-lb-13.6-kg.md
- src/pages/products/hills-perro-puppy-original-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-original-30-lb-13.6-kg.md
- src/pages/products/hills-perro-puppy-original-4.5-lb-2-kg.md
- src/pages/products/hills-perro-puppy-original-lata-0.82-lb-0.37-kg.md
- src/pages/products/hills-perro-puppy-small-bites-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-small-paws-15.5-lb-7-kg.md
- src/pages/products/hills-perro-puppy-small-paws-4.5-lb-2-kg.md
- src/pages/products/hills-perro-r-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-r-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-r-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-r-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-senior-vitality-7-12.5-lb-5.7-kg.md
- src/pages/products/hills-perro-senior-vitality-7-3.5-lb-1.6-kg.md
- src/pages/products/hills-perro-senior-vitality-7-5.95-lb-2.7-kg.md
- src/pages/products/hills-perro-u-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-u-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-w-d-17.6-lb-8-kg.md
- src/pages/products/hills-perro-w-d-27.5-lb-12.5-kg.md
- src/pages/products/hills-perro-w-d-3.3-lb-1.5-kg.md
- src/pages/products/hills-perro-w-d-8.5-lb-3.9-kg.md
- src/pages/products/hills-perro-z-d-ultra-17.6-lb-8-kg.md
- src/pages/products/hills-perro-z-d-ultra-8-lb-3.6-kg.md
- src/pages/products/plant1.md
- src/pages/products/plant2.md
- src/pages/products/plant3.md
- src/pages/products/plant4.md
- src/pages/products/plant5.md
- src/pages/products/plant6.md
- src/pages/products/plant7.md
- src/pages/products/plant8.md
- src/pages/products/plant9.md
